apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  labels:
    app: checkout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
        - name: checkout-service
          image: sha2121/shophub-checkout:k8s-v4
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: NODE_ENV
              value: "development"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "shophub_user"
            - name: DB_PASSWORD
              value: "shophub_pass"
            - name: DB_NAME
              value: "shophub"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBIT_URL
              value: "amqp://rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  selector:
    app: checkout-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
